estilo = turtle.Turtle()
estilo.speed(0)
estilo.color("white")
estilo.penup()
estilo.hideturtle()
estilo.goto(0, 260)
estilo.write("Jugador A: 0  Jugador B: 0", align="center", font=("Courier", 21, "normal"))
